import { Inter } from "next/font/google";
import "../globals.css";
import Topbar from "../components/Topbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Job Analyzer",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <div className="max-w-screen-2xl mx-auto w-[90%]">
          <Topbar/>
          {children}</div>
      </body>
    </html>
  );
}
